[package]
name = "openbrush_lang_codegen"
version= "4.0.0-beta.1"
authors = ["Brushfam <green@727.ventures>"]
edition = "2021"

license = "MIT"
repository = "https://github.com/Brushfam/openbrush-contracts"
documentation = "https://learn.brushfam.io/docs/openbrush"
homepage = "https://brushfam.io/"
description = "OpenBrush codegeneration for macros in `openbrush_lang_macro`."
keywords = ["wasm", "brushfam", "smart-contracts", "blockchain", "ink"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
syn = { version = "2.0.101", features = ["parsing", "full", "visit", "extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
serde_json = "1.0.140"
fs2 = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
cargo_metadata = "0.19.2"
unwrap = "1.2.1"
blake2 = "0.10.6"
heck = "0.5.0"
ink_ir = { version = "5.1.1", default-features = false }
ink_primitives = { version = "5.1.1", default-features = false }
synstructure = "0.13.2"

[lib]
name = "openbrush_lang_codegen"
path = "src/lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = []